import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ServerNavbar from "@/components/ServerNavbar";
import "./globals.css";
import "./styles/blog_search.css";
import "./styles/blogpost.css";
import "./styles/create_blog.css";
import "./styles/ia_assistance.css";
import "./styles/ia_response.css";
import "./styles/login.css";
import "./styles/main_page.css";
import "./styles/manage_perms.css";
import "./styles/navbar.css";
import "./styles/register.css";
import "./styles/toast.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ServerNavbar />
        {children}
      </body>
    </html>
  );
}
