// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/blog-search" | "/blog/[blogId]" | "/create-blog" | "/ia-assistance" | "/ia-response" | "/login" | "/manage_perms" | "/register"
type AppRouteHandlerRoutes = "/api/ai/consult" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/register" | "/api/auth/session" | "/api/blog-search" | "/api/blog/[blogId]" | "/api/blogs" | "/api/blogs/[blogId]" | "/api/blogs/images" | "/api/users"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/ai/consult": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/register": {}
  "/api/auth/session": {}
  "/api/blog-search": {}
  "/api/blog/[blogId]": { "blogId": string; }
  "/api/blogs": {}
  "/api/blogs/[blogId]": { "blogId": string; }
  "/api/blogs/images": {}
  "/api/users": {}
  "/blog-search": {}
  "/blog/[blogId]": { "blogId": string; }
  "/create-blog": {}
  "/ia-assistance": {}
  "/ia-response": {}
  "/login": {}
  "/manage_perms": {}
  "/register": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
